### ISSUE TITLE
Dead link to AMA in the OpenAPS documentation

### ISSUE THREAD

**Issue by bjornoleh** [openaps/AndroidAPSdocs#1011]
Hi, there is a dead link in this section which should be pointing to more info about AMA in the OpenAPS documentation

https://androidaps.readthedocs.io/en/latest/Usage/Open-APS-features.html#advanced-meal-assist-ama

The dead link:
https://openaps.readthedocs.io/en/latest/docs/walkthrough/phase-4/advanced-features#advanced-meal-assist-or-ama

Some quick googling returned this, is that the content that is missing? :

https://newer-docs.readthedocs.io/en/latest/docs/walkthrough/phase-4/advanced-features.html#advanced-meal-assist-or-ama

**Comment by xJoe** [comment]
Thanks, @bjornoleh.
Feel free to correct yourself next time as described in docs: https://androidaps.readthedocs.io/en/latest/make-a-PR.html
