### ISSUE TITLE
Icons not displayed or hard to see

### ISSUE THREAD

**Issue by jonaschn** [openaps/AndroidAPSdocs#1091]
The icons in the English versions are already hard to see:
https://androidaps.readthedocs.io/en/latest/Configuration/OmnipodEros.html#icons
![image](https://user-images.githubusercontent.com/9538230/148529528-70757ab2-9e98-4920-a242-db0587476cac.png)

The German page does not display the Icons at all:
https://androidaps.readthedocs.io/de/latest/Configuration/OmnipodEros.html#symbole
![image](https://user-images.githubusercontent.com/9538230/148529641-3a4d7170-132b-4a7b-bc9f-780ed333e6e2.png)

Tested with Desktop Mozilla FF.
Using a mobile phone, the icons are NOT visible in English as well!

**Comment by jonaschn** [comment]
The problem can be reproduced for the English desktop version when zooming in (133%).

**Comment by xJoe** [comment]
@teleriddler Could you please look into this. If I remember right you created the page. Thanks.

**Comment by peterleimbach** [comment]
I fixed it in the english version today.
@jonaschn => please check and give feedback.

@xJoe Please check the Crowdin translation

**Comment by peterleimbach** [comment]
@jonaschn Thanks for fast review.

I added the newlines with PR #1186.

**Comment by peterleimbach** [comment]
@xJoe Please check the German part in Crowdin.

**Comment by peterleimbach** [comment]
@xJoe Hi Jochen, please have a look at this and check it in translation too to finalize the issue.

**Comment by peterleimbach** [comment]
@xJoe Hi Jochen, please have a look at this and check it in translation too to finalize the issue.

**Comment by psonnera** [comment]
Fixed with https://github.com/openaps/AndroidAPSdocs/pull/1186
