### ISSUE TITLE
some doc update requests

### ISSUE THREAD

**Issue by intelli-perl** [openaps/AndroidAPSdocs#1112]
*Release notes for 3.0:
-bg data quality checks/constraints added

*a description of the data quality icons and what this means is missing, see https://www.facebook.com/groups/AndroidAPSUsers/permalink/3130354490519280/
@MilosKozak please help with a good wording for the documentation!

* https://androidaps.readthedocs.io/en/latest/Getting-Started/Screenshots.html
section H - Buttons
„ Buttons for insulin, carbs and Calculator are ‘always on’.“
thats incorrect. when connection to pump lost, insulin button is invisible. recommendation to switch to virtual pump

**Comment by xJoe** [comment]
Please use PR as descirbed in docs https://androidaps.readthedocs.io/en/latest/make-a-PR.html

**Comment by tanja3981** [comment]
The ticket was opened to request changes. To require a PR from someone asking for required information is closing some loop - the wrong way! ;-)

**Comment by xJoe** [comment]
@tanja3981 feel free to change

**Comment by tanja3981** [comment]
@xJoe If some developers could provide the necessary information, happy to write something. 🤷

**Comment by xJoe** [comment]
@MilosKozak & @Philoul 
Could one of you provide some details as requested by @intelli-perl and @tanja3981, please. Or inform which developer could provide the neccessary information on data quality icons. Thanks.

**Comment by tanja3981** [comment]
Could someone proof read this so I can create a PR?
@MilosKozak @xJoe @Philoul
https://github.com/tanja3981/AndroidAPSdocs/blob/bg-flag/docs/EN/Installing-AndroidAPS/update3_0.md#warning-signal-beneath-bg

**Comment by xJoe** [comment]
Tx. I'd add that yellow is constant when using Libre.

**Comment by tanja3981** [comment]
@xJoe done

**Comment by xJoe** [comment]
As PR is merged I close this issue.
