### ISSUE TITLE
Percentage profile is not correct

### ISSUE THREAD

**Issue by klalle** [openaps/AndroidAPSdocs#1126]
This is something that tricked me when going through the objective 3.
If you set a 90 % profile, the example states that the ISF is devided by 0.9, which is not a 10 % increase last time I checked... 
And the example image in the docs is also wrong (2.2/0.9 != 2.4) its more like 2.44444. (yes you have 2 digits on some numbers). but an 10 % increase would be: 2.2+0.22=2.42. 
![image](https://user-images.githubusercontent.com/4532449/153859682-e159c6ac-f249-447d-859b-d2d3b5152115.png)

Yes it's close to a 10 % increase, but lots of us are engineers, and we will have a hard time with this question since you'd have to answer wrong to get it right! Probably more than me that had to check the source-code to get this right ;) 
![image](https://user-images.githubusercontent.com/4532449/153860878-4832f29b-34ea-4746-9bd7-ded4475818c6.png)

To prove the point, lets take something larger: if you set a profile switch of 60 % (not even sure its posible) and an ISF of 10. 
10/0.6 = 16,6667, but a 40 % increase of 10 is 14.0!

Or am I misinterpreting this on some way?

**Comment by xJoe** [comment]
Where did you get the 10% from?

**Comment by klalle** [comment]
> Where did you get the 10% from?

![Screenshot_20220215-180844](https://user-images.githubusercontent.com/4532449/154112833-26bfabe4-ca49-4d08-a822-70089159d69f.png)
