### ISSUE TITLE
Phone used for "Sample setup" is no longer supported (running Android-Version 8.0)

### ISSUE THREAD

**Issue by vanelsberg** [openaps/AndroidAPSdocs#1212]
Phone used for "Sample setup" is no longer supported (S7 is running Android-Version 8.0)

See: _Sample setup: Samsung S7, Dana RS, Dexcom G6 and Sony Smartwatch_
https://androidaps.readthedocs.io/en/latest/Getting-Started/Sample-Setup.html#sample-setup-samsung-s7-dana-rs-dexcom-g6-and-sony-smartwatch

**Comment by peterleimbach** [comment]
I removed the sample setup.
