### ISSUE TITLE
YouTube link doesn't work

### ISSUE THREAD

**Issue by petervanrijt** [openaps/AndroidAPSdocs#1218]
Section [https://androidaps.readthedocs.io/en/latest/Hardware/DexcomG6.html#new-transmitter-with-running-sensor](https://androidaps.readthedocs.io/en/latest/Hardware/DexcomG6.html#new-transmitter-with-running-sensor) mentions YouTube video [https://youtu.be/AAhBVsc6NZo](https://youtu.be/AAhBVsc6NZo) . Opening the video shows 'This video is no longer available'. Does anyone have saved the source video?

**Comment by peterleimbach** [comment]
There are several videos available on YouTube how to do it. I think this is useful e.g. https://youtu.be/ANO0u5wChu0. Other people are using a credit card or something similar.

**Comment by petervanrijt** [comment]
Thanks! Tonight I saw soneone has changed video already to https://youtu.be/tx-kTsrkNUM which works. I'll close this issue.  All the best, Peter
