### ISSUE TITLE
BYOD support for Dexcom One

### ISSUE THREAD

**Issue by ilakisp** [openaps/AndroidAPSdocs#1241]
Hi all,
I am from Europe and I finally started getting coverage for dexcom cgm.
As fun as it is, several days and a couple of sensor later, I can't get that bloody thing to work in any way.
I have tried pretty much all possible options - apps (dexcom, xdrip, BYOD), all the settings.
I still have some hope that maybe BYOD could be the solution. But here's the issue - it does not currently support specifically Dexcom One. I imagine that implementation of it should not be complicated, as the product is basically the same.
Does anyone know if there's any hope for this, or should I be looking for alternatives altogether, as I am getting very tired with this? :)
Thanks!

**Comment by peterleimbach** [comment]
Hi ilakisp,

this is the place where we coordinate the work on the AndroidAPSDocs.

We are neither the AndroidAPS GitHub for the app nor the BYODA developers.

Please try to get an answer at one of the Facebook groups, Discord channels or the BYODA developers.

Thank you.
