### ISSUE TITLE
Confusing description of blue prediction line in screenshots section

### ISSUE THREAD

**Issue by suside** [openaps/AndroidAPSdocs#1297]
https://github.com/openaps/AndroidAPSdocs/blob/70708558f7fb10b0457131c99bbbfdb8d18e1e8e/docs/EN/Getting-Started/Screenshots.md?plain=1#L184

Is this :point_up: statement correct?

It seems to be contradictory with section below:
https://github.com/openaps/AndroidAPSdocs/blob/70708558f7fb10b0457131c99bbbfdb8d18e1e8e/docs/EN/Getting-Started/Screenshots.md?plain=1#L186

**So is it prediction of BG or IOB?**

Screenshot to visualise the problem, when TBR at 0% BG should rather rise not fall, right?
![image](https://user-images.githubusercontent.com/197044/193405267-2d94cdcd-270d-4048-b0d6-dd9e5661f345.png)
(from NS with OpenAPS mode)

**Comment by psonnera** [comment]
You're right, this is BG.
Corrected in https://github.com/openaps/AndroidAPSdocs/commit/c1f55d4c928746bbe064ba363c1149b1940acb0f

**Comment by suside** [comment]
If `the pump stopped all insulin delivery (0% TBR)` BG will eventually rise, therefore this is likely not BG prediction.

**Comment by psonnera** [comment]
@suside that depends on IoB. AFAIK Nightscout doesn't trace CoB curves, what would the scale be? Where in the graph above do you see carbs mentioned? (just trying to figure it out without looking into the code).

**Comment by suside** [comment]
1. I didn't mention carbs at all. I just said that without insulin BG will rise.
2. Your screenshot is great example of the issue, this situation makes no sense to me:
- Light blue - zero temp BG slightly rising
- Dark blue - IOB BG falling
3. (unrelated) Carbs based prediction is orange in NS:
![image](https://github.com/user-attachments/assets/43b80ef9-de75-4836-98fa-ae9f6a54cec9)

**Comment by psonnera** [comment]
@suside I am only trying to fix the documentation, except from https://github.com/openaps/AndroidAPSdocs/blob/70708558f7fb10b0457131c99bbbfdb8d18e1e8e/docs/EN/Getting-Started/Screenshots.md?plain=1#L186 do you see other mistakes? The actual AAPS prediction curves behavior should be addressed in https://github.com/nightscout/AndroidAPS

**Comment by suside** [comment]
> do you see other mistakes? 

Nope :+1:
