### ISSUE TITLE
US version of Libre 3 works with new Juggluco

### ISSUE THREAD

**Issue by emmatovar27** [openaps/AndroidAPSdocs#1334]
Hi,
Any admin can change the phrase that Libre 3 does not work with the US version.

I tested it on 10/1/2023, and it's working as expected. 

I followed the same steps and was able to broadcast the values from xDrip to AAPS. 
[Libre 3](https://wiki.aaps.app/en/latest/Hardware/Libre3.html)

**Comment by peterleimbach** [comment]
Closed with #1335
