### ISSUE TITLE
Wrong filename naming

### ISSUE THREAD

**Issue by tanja3981** [openaps/AndroidAPSdocs#1443]
PasswordReset file must be without spaces: 

https://androidaps.readthedocs.io/en/latest/Installing-AndroidAPS/update3_0.html#reset-master-password

https://androidaps.readthedocs.io/en/latest/Getting-Started/FAQ.html#how-to-reset-the-password-in-aaps-v3-x

This one is correct
https://androidaps.readthedocs.io/en/latest/Installing-AndroidAPS/update3_0.html#reset-master-password

**Comment by peterleimbach** [comment]
It should be fixed in case of questions please contact me.
