### ISSUE TITLE
Priorities on SMB settings page

### ISSUE THREAD

**Issue by ben80** [openaps/AndroidAPSdocs#1517]
I'd like to propose to adjust the description of the SMB settings starting from here (https://androidaps.readthedocs.io/en/latest/Usage/Open-APS-features.html#enable-smb). 
1) Change the order of how the settings are listed to reflect the order on the AAPS screen and the priority of how AAPS handles them
2) Highlight that "Enable SMB with high temp targets" has the highest priority
3) Highlight that you can either set "Enable SMB always" or use one or multiple of "Enable SMB with COB", "Enable SMB with temp targets", "Enable SMB after carbs"

**Comment by jbfeutz** [comment]
https://github.com/openaps/AndroidAPSdocs/pull/1552

**Comment by ben80** [comment]
I am not sure if some action is expected from me (i am the reporter of this issue).
The issue has been resolved and i support the changes. Thank you.
Am i supposed to close it? This one only or #1552 as well?

**Comment by psonnera** [comment]
@ben80 as far as I can see this has been worked on. Can you confirm it matches your request?
