### ISSUE TITLE
[suggestion] update the google sheet form: AAPS Omnipod DASH Hardware setups

### ISSUE THREAD

**Issue by FlyingToto** [openaps/AndroidAPSdocs#1565]
Few suggestions to improve the form:

1) from: "Smartphone Brand & Model"
to: "Smartphone Brand & Model & Provider: ie Samsung S22+ Tmobile"

2)in CGM choices add: G7
in CGM software add: BYODA-DIAKEM (G7 only)

3) in AAPS version: allow to enter the complete string so we can specify which version of dev specifically like "3.2.0-dev-i"

4) consider adding a question about "AAPS client display on watch Brand, Model,: Samsung GalaxyWatch4"

**Comment by vanelsberg** [comment]
@FlyingToto Thanks for you feedback!

1. I do not see how "GSM Provider" would relate to "Phone hardware is compatible with DASH"?

2. Will Add G7/DIAKEM

3. Version will only be "release version", with optional "dev" or "beta" tag signaling it was tested on a non-release version.

We really want to limit the versioning as with specific version/build info the entry will never be up-to-date and does not add to the "Phone hardware is compatible with phone". When a specific version/build has problems this is a bug that will eighter  solved or released resulting in the phone being marked "not compatible".

4. As this list is specific about registering Phones hardware tested to work with the Omnipod DASH pump I think this this question/information should be on a separate list for smartwatch or (more generic) accessory compatibility.

Could you please post this suggestion as a separate issue?

**Comment by FlyingToto** [comment]
Fair enough,
The reason why I mentioned the GSM provider might help is that the phone's android version is actually tied to the provider (at least in the US). For instance, Tmobile is the one deciding when to send the OTA update for my Samsung. TBH, I am not sure if people are having issues with Android udpates anymore, as long as the major version is the same it seems to work.

Will post a separate issue for tracking the watch versions. 

Thx!
