### ISSUE TITLE
Update G7 page with xDrip native mode

### ISSUE THREAD

**Issue by jbr7rr** [openaps/AndroidAPSdocs#1568]
xDrip+ can now also collect from the G7 directy, this works even for AAPS master. However xDrip+ does also not provide smoothing so a warning should be given and dev or beta1 recommended for smoothing (same as with patched G7 app)

xDrip+ reference:
https://navid200.github.io/xDrip/docs/Dexcom/G7.html

Discussion on discord:
https://discord.com/channels/629952586895851530/1114551522668322857

**Comment by FlyingToto** [comment]
yes, I am already looking at the overall xdrip page within the context of dexcom G6 & G7. But indeed as of now G7 support in AAPS is limited to beta/dev users.

**Comment by psonnera** [comment]
Added since https://github.com/openaps/AndroidAPSdocs/commit/1806126a901992d5eed4050dab58d9295c79cdba and modified afterwards.
