### ISSUE TITLE
check documentation and if necessary update for Libre 3 to get a good base for the rework-project

### ISSUE THREAD

**Issue by peterleimbach** [openaps/AndroidAPSdocs#1614]

**Comment by peterleimbach** [comment]
only this page - https://androidaps.readthedocs.io/en/latest/Hardware/Libre3.html

**Comment by jbfeutz** [comment]
I'll work on this one

**Comment by jbfeutz** [comment]
Draft here: https://docs.google.com/document/d/1EVEtg34QUjnPfgXwRHvPaVylR_q0-0QvgKWd7mVLsSI/edit?usp=sharing

**Comment by psonnera** [comment]
From https://github.com/openaps/AndroidAPSdocs/commit/c6fbd1275f950f43ca5382d25687a5b6e18094c6 onwards
