### ISSUE TITLE
check documentation and if necessary update for Dexcom G7 to get a good base for the rework-project

### ISSUE THREAD

**Issue by peterleimbach** [openaps/AndroidAPSdocs#1616]
https://androidaps.readthedocs.io/en/latest/Hardware/DexcomG7.html

Please PR on the branch rework-project.

**Comment by FlyingToto** [comment]
I can work on this part of the doc.

**Comment by psonnera** [comment]
https://github.com/openaps/AndroidAPSdocs/commit/0cd9bab2ec1c10044af26bbb3f6b6feb2c92d7df
