### ISSUE TITLE
check documentation and if necessary update for Dana RS and I to get a good base for the rework-project 

### ISSUE THREAD

**Issue by peterleimbach** [openaps/AndroidAPSdocs#1620]
this page please - https://androidaps.readthedocs.io/en/latest/Configuration/DanaRS-Insulin-Pump.html

If you can only check for one pump do it and comment though the next can do the rest.

**Comment by xToSchx** [comment]
Reviewed and updated. PR created.

**Comment by peterleimbach** [comment]
Can't find the PR at the moment. Which number does it have?

**Comment by peterleimbach** [comment]
Please PR on the branch rework-project.

**Comment by xToSchx** [comment]
Re-created PR for rework-project ;-) Initial request was for 'master' (closed this one in the meantime).

**Comment by peterleimbach** [comment]
closed with #1622
