### ISSUE TITLE
updating Preparing/Requirements

### ISSUE THREAD

**Issue by FlyingToto** [openaps/AndroidAPSdocs#1624]
few questions regarding the documentation on requirements:

@MilosKozak, @peterleimbach, 

1. I assume we can add android 13 in the list of supported versions, correct?
2. What about older android version 9 is that still ok from the current branch?
3. is it still possible to use AAPS with versions of Android older than 8 from the old repository with 2.6.1.4?
4. BTW is our documentation still valid for these older builds since we keep updating, devices, screenshots etc...?

Targeted text to refresh : 

> _"The current version of AAPS requires an Android smartphone with Google Android 9.0 or above. So if you are thinking about a new phone, Android 9 is recommended at a minimum but optimally choose Android 10 or 12. Users are strongly encouraged to keep their build of AAPS up to date for safety reason, however for users unable to use a device with a minimum version of Android 8.0, AAPS version 2.6.1.4, suitable for older Android versions, remains available from the [old repository.](https://github.com/miloskozak/AAPS)"_

**Comment by psonnera** [comment]
I'd like to turn the page on older versions to make sure the documentation is up to date with the current AAPS version.
For this, there is now a link to 3.1 https://androidaps.readthedocs.io/en/3.1/ in ReadTheDocs.
The section is being updated in prevision of 3.3 https://androidaps.readthedocs.io/en/latest/Getting-Started/Phones.html#phones
