### ISSUE TITLE
html link missing in FullClosedLoop.html

### ISSUE THREAD

**Issue by jmKeenan** [openaps/AndroidAPSdocs#1640]
On this page https://androidaps.readthedocs.io/en/latest/Usage/FullClosedLoop.html there are two references to study:

A modelling study (details see LINK FullLoop V2/March2023; there section 2.2) can show in quantitative terms that faster insulins

But the link is not provided, is it possible to add the HTML link?

**Comment by peterleimbach** [comment]
I need to ask the author off-line. A moment please.

**Comment by peterleimbach** [comment]
@jmKeenan This should be the link. Can you please check if it is complete from your point of view. Sorry busy with technical stuff at the moment.

**Comment by psonnera** [comment]
https://github.com/openaps/AndroidAPSdocs/commit/b03d12818bb15ebca84710059c28c29f7489f205
