### ISSUE TITLE
Understanding Screens -> Section E

### ISSUE THREAD

**Issue by kraftm1989** [openaps/AndroidAPSdocs#167]
I did not understand the explanation of the prediction lines under "section e".
At https://androidaps-altguide.readthedocs.io/en/latest/pages/Screenshots.html?highlight=section%20e I find this better explained.
Would it be OK to add this description here?

**Comment by AdrianLxM** [comment]
The "altguide" has not gone through any review - nor is the license clear.
It copies from the AndroidAPS docs that are GPL and the OpenAPS docs that is MIT License and also from the Loop docs that I don't know the license from and uses a different algorithm anyway.

The description in Section E of the referenced page has more information but not necessarily the correct information. COB is somehow semi-correct, "Dark blue" and "light blue" are totally mixed up.

**Comment by kraftm1989** [comment]
ok, but would it not be possible and meaningful to make the documentation more understandable at this point?

**Comment by AdrianLxM** [comment]
Yes, definitely. I just merged a PR from Tim that should help a bit: https://github.com/openaps/AndroidAPSdocs/pull/168
