### ISSUE TITLE
Add a more detailed diagram of data flow

### ISSUE THREAD

**Issue by yossibivas11** [openaps/AndroidAPSdocs#1717]
A while back I made this higher detail diagram of the flow of data from sensor>AAPS>pump etc.
I think it might be useful in the site

![254522386_10159497539834096_3235242753522916874_n](https://github.com/openaps/AndroidAPSdocs/assets/48336526/eefc1949-8880-43cc-ad04-789a874993b5)

**Comment by jbr7rr** [comment]
I think this diagram is too detailed. Information gets outdated quickly. for example on your diagram Ruffy is not needed in AAPS 3.2, and will be completely removed in AAPS 3.3. Same goes for eversense there are now new ways for it. And lets not forget the plethora of pumps available for AAPS

**Comment by psonnera** [comment]
All in one is too many, we tried to split, this is the sensor side for example https://androidaps.readthedocs.io/en/latest/preparing.html#cgm-sensor-app
