### ISSUE TITLE
How to replace EN screenshot with translated version? 

### ISSUE THREAD

**Issue by sheh1000** [openaps/AndroidAPSdocs#1960]
So we have many screenshots in English language. 
For example, I want to upload a translated RU version of the first screenshot (table) from this Doc page: https://androidaps.readthedocs.io/ru/latest/Usage/temptarget.html
Image link is https://github.com/openaps/AndroidAPSdocs/assets/137224335/73eeadf1-c17e-4955-afd8-f49c281331e3

A wasn't able to find the related media image on Crowdin and Giltab repository. Is there any way to upload translated screenshot for the page I mentioned above?

**Comment by psonnera** [comment]
Images are slowly being modified to remove text, tables, etc... to make translators work easier as image translation is not fully implemented. I commit on removing most of the text based images before 3.3 release.
