### ISSUE TITLE
Switching language is broken in AndroidAPS docs

### ISSUE THREAD

**Issue by sheh1000** [openaps/AndroidAPSdocs#1992]
Open any doc page and try to switch any language, anyway it will be shown in English
Examples: 
https://androidaps.readthedocs.io/ru/latest/introduction.html
https://androidaps.readthedocs.io/de/latest/introduction.html

We reported about this ussue 15 days ago in [Crowdin discussions](https://crowdin.com/project/androidapsdocs/discussions/8)
The issue frustrates many translators - we spend literally months to translate docs, and now these results aren't visible to any user of AndroidAPS.

**Comment by anbraten** [comment]
I would like to investigate into this one, unfortunately I am currently missing access to crowdin to help.

**Comment by psonnera** [comment]
I cannot see this issue anymore. Marking fixed. Please reopen if I'm wrong.
