### ISSUE TITLE
Issue with link on Preparing page

### ISSUE THREAD

**Issue by emilisev** [openaps/AndroidAPSdocs#2016]
In the Preparing page, there is the following sentence : 
`How long it takes to get to closed looping depends on the individual, but an approximate timescale for getting to full looping with AAPS can be found (here)`

But there is no link under "here". I can see a link in crowdin though, but it's not showing in the live page...

**Comment by psonnera** [comment]
Looks like it got overwritten. https://github.com/openaps/AndroidAPSdocs/commit/7feb6f75e7fab87651defceffa581be9842f72e1
