### ISSUE TITLE
Enable pdf and epub export

### ISSUE THREAD

**Issue by vnniyB** [openaps/AndroidAPSdocs#2031]
I was speaking to my endo the other day, he was wanting to export the docs to pdf to print out to go over with other patients and also for himself.
I noticed read on read the docs that there is a standard config for enabling this.
https://docs.readthedocs.io/en/stable/downloadable-documentation.html

Seems like a handy feature, also for anyone needing to read offline :)

**Comment by vnniyB** [comment]
Mr here
https://github.com/openaps/AndroidAPSdocs/pull/2032

**Comment by psonnera** [comment]
Looking this PR now and only wondering about the risk linked with having obsolete pdf documents around as the main documentation is still under heavy rework

**Comment by psonnera** [comment]
Declined as in PR.
