### ISSUE TITLE
Untranslated admonition does not show at all on live page

### ISSUE THREAD

**Issue by emilisev** [openaps/AndroidAPSdocs#2053]
I have noticed that when translation are missing for admonition or other blocks with specific classes, these blocks do not show at all in the live doc page. This seems like a safety issue, because important information are not shown, even in english.

Ex : In Preferences page, under NS v3, we have this admonition : https://androidaps.readthedocs.io/en/latest/Configuration/Preferences.html#nsclientv3
![image](https://github.com/user-attachments/assets/ad1890aa-6470-4f3c-858b-8d78263c252e)

In French page, it does not show at all : https://androidaps.readthedocs.io/fr/latest/Configuration/Preferences.html#nsclientv3
![image](https://github.com/user-attachments/assets/f2176b1e-e6f4-4e3a-a77c-eb8d75533469)

This is a single example, but I have seen this repeatedly on other pages.

**Comment by psonnera** [comment]
We're addressing issues with Crowdin propagation now. Stay tuned.

**Comment by psonnera** [comment]
Yes. Where the admonition class is set like that in EN:

```
:::{admonition} V3 data uploaders
:class: warning
When using NSClientV3, all uploaders must be using the API V3. Since most are not compatible yet, this means **you must let AAPS upload all data** (BG, treatments, ...) to Nightscout and disable all other uploaders if they're not V3 compliant.  
:::
```

Crowdin forgets a space and the parser fails understanding the unknown class name

```
:::{admonition} V3 data uploaders
:class: warning When using NSClientV3, all uploaders must be using the API V3. Since most are not compatible yet, this means **you must let AAPS upload all data** (BG, treatments, ...) to Nightscout and disable all other uploaders if they're not V3 compliant.  
:::
```

**Comment by psonnera** [comment]
Got it. That's badly converted from doc migration. myST adminitions recommendations are:
It is advised to use admonitions with the [colon_fence](https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#syntax-colon-fence) extension, which signify that the content of the block is also MyST Markdown.
Will fix that (might take some time to catch them all)

**Comment by psonnera** [comment]
Should be fixed with https://github.com/openaps/AndroidAPSdocs/commit/9689da225cefaa58e7cfc74f2c2285bbc5fe8b4f
@emilisev please let me know

**Comment by emilisev** [comment]
Not sure if it's all good, with crowdin. Or maybe a side effect. In preparing.md, at the very bottom, in the original file, we have : 
`
```{admonition} Google Play Protect potential Issue
:class: warning
There have been several reports of **AAPS** being shut down arbitrarily by Google Play Protect every morning. If this happens you will have to go to the google play options and disable “Google Play Protect”. Not all  phone models or all Android versions are affected..
```
`

But in crowdin, the "Google Play Protect potential Issue" string does not show anymore for translation : 
![image](https://github.com/user-attachments/assets/cf44e031-5992-4be8-bf95-b53559520aa8)
