### ISSUE TITLE
Discord Channel link is bad

### ISSUE THREAD

**Issue by maddog0487** [openaps/AndroidAPSdocs#2056]
Hello, also on Objective 3 and trying to connect with the community on Discord for hints, however the link provided in the documention in bad and doesn't lead anywhere.

**Comment by maddog0487** [comment]
Hi Patrick,  There is a link in the intro section of the docs... the first one in your email, it didn't work.  However, I did come across the second link further one and it allowed me to join the channel.
-------- Original message --------From: Patrick Sonnerat ***@***.***> Date: 2024-09-18  3:52 a.m.  (GMT-05:00) To: openaps/AndroidAPSdocs ***@***.***> Cc: maddog0487 ***@***.***>, Author ***@***.***> Subject: Re: [openaps/AndroidAPSdocs] Discord Channel link is bad (Issue #2056) 
Works for me https://discord.com/channels/629952586895851530/629954570394533889 maybe you need the invitation https://discord.gg/zg7CvCQ please try and let me know.

**Comment by psonnera** [comment]
The second one is the invitation I provided or something else?

**Comment by maddog0487** [comment]
The second link is listed in a different location in the docs, Other Resources in English but the first link is early on in the Intro and you need to have previously set up the Discord login for it to work.

**Comment by psonnera** [comment]
Got it https://androidaps.readthedocs.io/en/latest/preparing.html#ask-on-the-aaps-discord-channel let me replace it with the invitation

**Comment by psonnera** [comment]
https://github.com/openaps/AndroidAPSdocs/commit/0b7ebcf5976907f73700283e16f2110c9824ed4a
