### ISSUE TITLE
Add Traditional Chinese (zh_TW)  Language

### ISSUE THREAD

**Issue by Angus-repo** [openaps/AndroidAPSdocs#2089]
Hi,

I have two things to report:

1. In CROWDIN, Traditional Chinese (zh_TW) has been added, but on GitHub, there is only a two-letter language directory (docs/CROWDIN/zh). This has caused both Traditional Chinese (zh_TW) and Simplified Chinese (zh_CN) to be written into the same "zh" directory, resulting in the two languages overwriting each other. Could you help create complete language directories?

![image1](https://github.com/user-attachments/assets/2f6a0d40-2891-4c32-add5-368c629a8624)
![image2](https://github.com/user-attachments/assets/0cdb4e4e-4e7d-49d3-bc85-32d26ddae5ec)

2. The Traditional Chinese (zh_TW) translation is 99% complete. Could you assist in setting it up so users can select the zh_TW language? Thank you.

![image3](https://github.com/user-attachments/assets/3392f73c-8859-4112-814b-bb70539439b3)

Thank you so much for your help and hard work!

**Comment by Angus-repo** [comment]
![圖片](https://github.com/user-attachments/assets/f7c434e1-0029-4ee7-825f-200c65a6f55a)

I have found a method to convert %two_letters_code% to a custom code in Crowdin. Could someone with the appropriate permissions please assist with the setup?

In Crowdin, navigate to Settings > Languages > Language Mapping, and enter the following configurations:

-     Language: Traditional Chinese
      Placeholder: two_letters_code
      Custom Code: zh_TW

-     Language: Simplified Chinese
      Placeholder: two_letters_code
     Custom Code: zh_CN

Thank you for your assistance.

**Comment by psonnera** [comment]
Please check if it's what you needed, https://androidaps.readthedocs.io/zh-tw/latest/

**Comment by Angus-repo** [comment]
Thank you very much
