### ISSUE TITLE
Menu documentation

### ISSUE THREAD

**Issue by kateLint** [openaps/AndroidAPSdocs#2179]
- A detailed record of what user ate throughout the day, divided by meals.
- Can be by integration with external apps like Calory, or develop from scratch.
- Link the meal records to the visualization of the data reports on the graphs.

**Comment by psonnera** [comment]
@kateLint is this related to the documentation (then please mention the pages name) or the AAPS application (in this case it's somewhere around here https://github.com/nightscout/AndroidAPS/issues)

**Comment by psonnera** [comment]
Closing this issue due to lack of feedback. As written above I believe it's a feature request.
