### ISSUE TITLE
Big time difference Unihertz Jelly Star + DanaRS

### ISSUE THREAD

**Issue by chrissie7** [openaps/AndroidAPSdocs#2247]
Hi, 
I keep getting the message that there is a big time difference between pump and smartphone, but every time I check the time, pump and smartphone have the same time, not even one minute difference. 
What I tried so far:
•	automatic timezone --> off
•	automatic time -->off
•	Pump clear history
•	unpair and pair pump
•	Phone power off and on a few times a day
•	Reset smartphone and install new build AAPS
•	Change language settings in English

I had this alarm with two different Dana RS pumps (6yrs old and 2 yrs old) and two different smartphones (Unihertz Jelly Star + Unihertz Jelly 2)

Phone is always in airplane mode, only online 1-2x per week for data upload.
I‘ve attached pictures and the last log, alarm occured at : 10:31:09.536

Thanks.
Christina
![1734602728890](https://github.com/user-attachments/assets/8e15d494-8ca7-4af6-882f-c2c7c54f84fd)
![1734602728901](https://github.com/user-attachments/assets/bee240e0-a1b4-4cb3-9ee8-6cef4336fd06)
![1734602728911](https://github.com/user-attachments/assets/6793108d-0e07-4d6e-9177-97fe471dd51d)
![1734602978355](https://github.com/user-attachments/assets/b301d75d-e462-4654-9e57-14b12be408df)
![1734602978368](https://github.com/user-attachments/assets/97789e85-c298-4752-9c4f-604126eadcd4)
[AndroidAPS._2024-12-19_10-36-13_.16.txt](https://github.com/user-attachments/files/18196431/AndroidAPS._2024-12-19_10-36-13_.16.txt)

**Comment by psonnera** [comment]
@chrissie7 unless this is a documentation issue, it might not be the right place to report this. Can you repost it in https://github.com/nightscout/AndroidAPS/issues?

**Comment by chrissie7** [comment]
Oh sorry, I didn't notice I'm on the wrong place here. I will close this issue and repost it. Thanks.
