### ISSUE TITLE
Max IOB example is misleading

### ISSUE THREAD

**Issue by Kywalh** [openaps/AndroidAPSdocs#249]
In the documentation, when dealing with maxIoB the example used as a starting point says : max daily basal...
This can be understood as total daily basal ...
Could be rephrased with something like max hourly basal rate...
Issue also raised in OpenAPS

**Comment by AdrianLxM** [comment]
This is a term in the app, so I believe we should keep it in the documentation like it is in the app.

For discussion about the the app please use the app's repo. This repo is hardly read by anyone.
