### ISSUE TITLE
surreptitious advertising

### ISSUE THREAD

**Issue by kraftm1989** [openaps/AndroidAPSdocs#539]
I find the surreptitious advertising for mevita.de in the image of the basal rate profile inappropriate and would like to suggest to remove the image, or to remove the link.

**Comment by xJoe** [comment]
https://androidaps.readthedocs.io/en/latest/EN/Usage/Objectives.html#objective-5-tuning-the-closed-loop-raising-max-iob-above-0-and-gradually-lowering-bg-targets
