### ISSUE TITLE
License Issues

### ISSUE THREAD

**Issue by AdrianLxM** [openaps/AndroidAPSdocs#54]
The main content of this Wiki is licensed under "GNU AFFERO GENERAL PUBLIC LICENSE - Version 3, 19 November 2007".

When creating this repository there has happened that MIT-License was set. This means we would have to ask all (unknown) authors of the old wiki. IMHO the easiest way would be to go back to the original license.

@danamlewis , @typ1-brods , @jotomo , @scottleibrand , @Lillycgm , @roppenheimer, you have been doing edits in the meantime. Are you ok with going back to the original license?

**Comment by Lillycgm** [comment]
It’s ok on my behalf😘

**Comment by typ1-brods** [comment]
Yes for sure. I have made changes for the community, not for intellectual property reasons :-)

**Comment by jotomo** [comment]
Fine by me as well

On July 9, 2018 3:17:39 PM GMT+02:00, AdrianLxM <notifications@github.com> wrote:
>The main content of this Wiki is licensed under "GNU AFFERO GENERAL
>PUBLIC LICENSE - Version 3, 19 November 2007".
>
>When creating this repository there has happened that MIT-License was
>set. This means we would have to ask all (unknown) authors of the old
>wiki. IMHO the easiest way would be to go back to the original license.
>
>@danamlewis , @typ1-brods , @jotomo , @scottleibrand , @Lillycgm ,
>@roppenheimer, you have been doing edits in the meantime. Are you ok
>with going back to the original license?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/openaps/AndroidAPSdocs/issues/54

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by roppenheimer** [comment]
Yes, makes no difference to me.

 

R.
