### ISSUE TITLE
Screenshots page does not appear in RTD index

### ISSUE THREAD

**Issue by roppenheimer** [openaps/AndroidAPSdocs#63]

**Comment by typ1-brods** [comment]
Rename file /EN/Getting-Started/screenshots.md to Screenshots.md and delete the /EN/Getting-StartedScreenshots.md file

**Comment by typ1-brods** [comment]
Maybe - as I wrote before - you have to delete the Getting Started Screenshots file in /EN/ directory because RTD has a problem with files and subdirectories that have the same name. Here only the / differs

**Comment by typ1-brods** [comment]
Working now. You are welcome! Issue should be closed
