### ISSUE TITLE
NSClient documentation does not reflect actual behavior

### ISSUE THREAD

**Issue by musicman0329** [openaps/AndroidAPSdocs#739]
Referencing this thread in the AndroidAPS FB group... 
https://www.facebook.com/groups/AndroidAPSUsers/permalink/2616961101858624/

The AAPS documentation (right now) indicates that NSClient is intended to be used for remote monitoring and downloads all data (IOB/COB included) that is uploaded to NS by the master phone. 

It appears that this is not actually the current behavior of the NSClient app, which performs its own IOB/COB calculations based on the settings configured in the app. If these settings differ from the master phone (or OpenAPS rig, in my case) in any way, then the results of the calculations performed by the NSClient app will produce different results from the master phone, potentially leading to a life threatening situation if a remote caregiver treats based on data displayed in the NSClient app. 

These two screenshots show the mismatch in IOB.
![Screenshot_20200202-113622](https://user-images.githubusercontent.com/15910886/73686702-81816100-4696-11ea-9444-512e7416bbdc.png)
![Screenshot_20200202-113612](https://user-images.githubusercontent.com/15910886/73686703-81816100-4696-11ea-8f00-600531588ff9.png)

These two screenshots illustrate the mismatch in COB (as reported by the OpenAPS rig) and the COB reported by NSClient. 
![Screenshot_20200203-123504](https://user-images.githubusercontent.com/15910886/73686817-bab9d100-4696-11ea-852b-315c2b2f356b.png)
![84141493_1036080293444552_7397697751334518784_o](https://user-images.githubusercontent.com/15910886/73687007-18e6b400-4697-11ea-9685-c78978de96f6.jpg)

**Comment by musicman0329** [comment]
Relevant link to AndroidAPS documentation -
https://androidaps.readthedocs.io/en/latest/EN/Children/Children.html

**Comment by xJoe** [comment]
Information added that settings must be same on master and follower phone and to consider time gap.
See also https://github.com/MilosKozak/AndroidAPS/issues/2425
