### ISSUE TITLE
URL in Install-Git is just for Windows

### ISSUE THREAD

**Issue by MarieT1D** [openaps/AndroidAPSdocs#781]
The URL for the git-download is just for Windows users. So I suggest:
- mention that it is just for windows
- or use https://git-scm.com/download/ instead of https://git-scm.com/download/win for anyone. 
- or use the URLs for Windows AND MacOS, Linux-Users should know how to do it 

- I would mention that also step 3 (Path to get executable) is an example for windows as (git).exe is for windows, so MacOS-users with just few knowledge might not know why .exe is written there
- also in the first sentence: "Let Studio know where is git.exe located: File - Settings" 'git.exe' is mentioned, which is just for Windows, not MacOS/Linux

File:
https://github.com/openaps/AndroidAPSdocs/blob/master/docs/EN/Installing-AndroidAPS/git-install.rst

**Comment by xJoe** [comment]
Feel free to update- ;-)
