### ISSUE TITLE
maxSMBBasalMinutes misleading description

### ISSUE THREAD

**Issue by Rhabarbara745** [openaps/AndroidAPSdocs#876]
In the latest version of the docs `maxSMBBasalMinutes` is descriped as followed:

> This is an important safety setting. This value determines how much SMB can be given based on the amount of basal insulin in a given time, **when it is not covered by COBs**.  

https://androidaps.readthedocs.io/en/latest/EN/Usage/Open-APS-features.html

According to
https://github.com/MilosKozak/AndroidAPS/blob/08730dfc9a73fa9317a162a41c66a7bc9d2bb387/app/src/main/assets/OpenAPSSMB/determine-basal.js#L1048-L1054

`maxSMBBasalMinutes` is only used if `mealInsulinReq >= iob_data.iob`.
Otherwise `maxBolus` seems to be calculated with the hardcoded value `30`.

This means to me if all COBs are covered with Insulin, SMBs can't be bigger than `maxSMBBasalMinutes = 30` regardless of what value is set in `maxSMBBasalMinutes`.

**Comment by typ1-brods** [comment]
Thanks for the hint! Fixed

https://github.com/openaps/AndroidAPSdocs/commit/42132a0aa47b51288fc0fd1d89a160b845cb69fe
