### ISSUE TITLE
Nightscout setup page is pointing to an obsolete link

### ISSUE THREAD

**Issue by psonnera** [openaps/AndroidAPSdocs#905]
https://androidaps.readthedocs.io/en/latest/EN/Installing-AndroidAPS/Nightscout.html#manual-nightscout-setup is pointing to Nightscout.info with mLab database add-on. That doesn't work anymore since it was removed beginning of this month. Please update to http://nightscout.github.io/nightscout/new_user/ or any preferred method.

**Comment by xJoe** [comment]
Will be updated with next build. Tx.
