### ISSUE TITLE
Spanish Dev Version: building and updating apk are under the reversed topic

### ISSUE THREAD

**Issue by MarieT1D** [openaps/AndroidAPSdocs#94]
I don't speak Spanish, but as far as I can see, in 'Compilanda la APK', you can read how to update the akp and in  'actualiza......' you can read how to compile the akp

**Comment by Lillycgm** [comment]
"compilando la APK" is  building the apk and "actualizando..." is how to update to new version. maybe you get confuse because first line it says "instalando" which stands for installing on both docs but you can see same expresion in english.

**Comment by MarieT1D** [comment]
![unbenannt](https://user-images.githubusercontent.com/37214302/43397837-76e9b088-9406-11e8-98ec-945d2a625e0f.JPG)
![unbenannt2](https://user-images.githubusercontent.com/37214302/43397849-7c9e8dc8-9406-11e8-8278-94bb3d930311.JPG)
It is the menu on the left which confuses me. In the menu 'compilando la APK' you find the same points as in the old wiki 'update to new version'  and in the menu Point 'actualizar a una nueva versión', you find 'compilando la APK'

**Comment by MarieT1D** [comment]
I'm closing the issue, because of the new crowding project, we need to transfer the translation anyway
