### ISSUE TITLE
NSClient app - more info needed

### ISSUE THREAD

**Issue by szantos** [openaps/AndroidAPSdocs#973]
Hi,
I'd like to address some minor issues regarding the NSClient app:

**1) Naming confusion**
It should be made clear whether the NSClient module (of AAPS) is meant or the NSClient app.

**2) Download location of NSClient app**
Can't be found in the doc.

**3) Difference between NSClient and NSClient2 apk**
I've found on Gitter:
Only difference is the app name. This way you can install the app twice on the same phone. You can follow 2 different persons/nightscouts with it.

**4) NSClient app related to AAPS**
A few sentences would be great about it pointing out the key differences: stripped down AAPS, etc.

---------------

We are using a system of Dexcom G6, Accu-Chek Combo, Nightscout, xDrip+, AAPS and NSClient app for a few months. Until now NSClient app seems to be the best way to follow somebody, as it can display all info including current insulin activity, and allows some interaction (profile, TT). Taking this into account, the app is not "advertised" enough. I've randomly came across the download location, and had to try NSClient and NSClient2, as I didn't know the diff.

Best regards

// and great appreciation for all the work done

**Comment by xJoe** [comment]
https://androidaps.readthedocs.io/en/latest/EN/make-a-PR.html
